version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
      time: "13:25"
      timezone: Etc/UCT
#    reviewers:
#      - "Johannes-Schneider"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "com.github.ekryd.sortpom:sortpom-maven-plugin" # newer versions require Java > 8
      - dependency-name: "net.revelc.code.formatter:formatter-maven-plugin" # newer versions require Java > 8
      - dependency-name: "net.revelc.code:impsort-maven-plugin" # newer versions require Java > 8
      - dependency-name: "org.mockito:mockito-core" # newer versions require Java > 8
