name: Build with Maven

on:
  workflow_call:
    inputs:
      mavenProfile:
        description: "The Maven profile to use to build the project."
        required: false
        type: string
      mavenModules:
        description: "The Maven module that should be built with following syntax: ':<module-name>(opt:,:<further-module-name>')*. Example: ':module-1,:module-2'."
        required: false
        type: string
      skipGpg:
        description: "Indicates whether the GPG signing should be skipped."
        required: false
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8, 11 ]
    name: Build with Java ${{ matrix.java-version }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java-version }}
      - name: Build with Maven
        run: |
          echo "profile=''" >> $GITHUB_ENV
          echo "modules=''" >> $GITHUB_ENV
          echo "skipGpg=''" >> $GITHUB_ENV
          
          if [ -n "${{ inputs.mavenProfile }}" ]; then
            echo "profile='-P ${{ inputs.mavenProfile }}'" >> $GITHUB_ENV
          fi
          
          if [ -n "${{ inputs.mavenModules }}" ]; then
            echo "modules='-pl ${{ inputs.mavenModules }}'" >> $GITHUB_ENV
          fi
          
          if [ "${{ inputs.skipGpg }}" = "true" ]; then
            echo "skipGgp='-Dgpg.skip'" >> $GITHUB_ENV
          fi
          
          mvn clean install $profile $modules $skipGpg
          
          
          
          
