---
name: Bump Project Version V2

on:
  workflow_dispatch:
    inputs:
      updateType:
        description: "The type of version bump that should be performed"
        required: true
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CLOUD_SDK_AT_SAP_ALL_ACCESS_PAT }}

      - name: Bump Version
        uses: DigitalToolsManufactory/gh-action-maven-bump-version@v1
        id: bump-version
        with:
          bumpType: "${{ inputs.updateType }}"
          pomFiles: "pom.xml bom/pom.xml modules-bom/pom.xml"

      - name: Commit Changes
        id: git-commit
        run: |
          git config --global user.email "cloudsdk@sap.com"
          git config --global user.name "SAP Cloud SDK"
          
          branch_name=version-bump/$(date +%s)
          echo "::set-output name=branch-name::$branch_name"
          
          git checkout -b "$branch_name"
          git commit -am "bump version"
          git push --set-upstream origin "$branch_name"

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          source_branch: ${{ steps.git-commit.outputs.branch-name }}
          pr_title: "Bump Version: `${{ steps.bump-version.outputs.old_version }}` -> `${{ steps.bump-version.outputs.new_version }}"
          pr_draft: false
          github_token: ${{ secrets.CLOUD_SDK_AT_SAP_ALL_ACCESS_PAT }}

