name: dependabot merger

on:
  pull_request:
    branches: [ 145-automate-dependabot ] #for testing, change to 'main' before final commit

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: check ci build
        id: check-ci
        run: |
          # GET check run for ci-build
          check_run=$(curl -s \
          -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
          "https://api.github.com/repos/${{github.repository}}/commits/${{github.event.pull_request.head.sha}}/check-runs?check_name=Java CI with Maven" \
          
          # Get raw conclusion from check run, first result
          check_status=$(echo "$check_run" | jq -r '.check_runs[0].conclusion')
          
          # Set output of step to status
          echo"::set-output name=check_ci::$check_status"

      - name: check codeql scan
        id: check-codeql
        run: |
          # GET check run for ci-build
          check_run=$(curl -s \
          -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
          "https://api.github.com/repos/${{github.repository}}/commits/${{github.event.pull_request.head.sha}}/check-runs?check_name=CodeQL Scan" \
          
          # Get raw conclusion from check run
          check_status=$(echo "$check_run" | jq -r '.check_runs[0].conclusion')
          
          # Set output of step to status
          echo"::set-output name=check_codeql::$check_status"

  review-pr:
    runs-on: ubuntu-latest
    needs: checks
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' &&
      needs.checks.outputs.check_ci == 'success' &&
      needs.checks.outputs.check_codeql == 'success'}}
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.3.1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
      - name: approve
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: enable auto-merge for dependabot PRs
        # Condition? All PRs or only patches?
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
