name: Release to Maven Central

on:
  workflow_dispatch:
    inputs:
      updateType:
        description: "The type of version bump that should be performed"
        required: true
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    runs-on: ubuntu-latest
    name: Perform Release
    needs: checkout
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
        with:
          token: ${{ secrets.CLOUD_SDK_AT_SAP_ALL_ACCESS_PAT }}

      - uses: actions/setup-java@v2
        name: Setup JDK
        with:
          distribution: 'adopt'
          java-version: 8

      - name: Bump Version
        uses: DigitalToolsManufactory/gh-action-maven-bump-version@v1
        id: bump-version
        with:
          bumpType: "${{ inputs.updateType }}"
          pomFiles: "pom.xml bom/pom.xml modules-bom/pom.xml"

      - name: Build Project
        run: mvn clean install -P release -Dgpg.skip

      - name: Commit Changes
        id: git-commit
        run: |
          git config --global user.email "cloudsdk@sap.com"
          git config --global user.name "SAP Cloud SDK"
          
          git commit -am "bump version ${{ steps.git-commit.outputs.old_version}} -> ${{ steps.git-commit.outputs.new_version}}"
          git tag -m "Release v${{ steps.git-commit.outputs.new_version}}" -a "v${{ steps.git-commit.outputs.new_version}}"
          git push --follow-tags

      - name: Deploy Release
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.CLOUD_SDK_AT_SAP_PRIVATE_GPG_KEY }}
          gpg_passphrase: ${{ secrets.CLOUD_SDK_AT_SAP_PRIVATE_GPG_PASSPHRASE }}
          nexus_username: ${{ secrets.CLOUD_SDK_AT_SAP_NEXUS_USER }}
          nexus_password: ${{ secrets.CLOUD_SDK_AT_SAP_NEXUS_PASSPHRASE }}
          maven_profiles: "release"
